language: node_js
sudo: false
dist: trusty

node_js:
  - "node"

env:
  - CXX=g++-4.8 HUGO_VERSION=0.30


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  webhooks:
    urls:
      # FIXME this is really not a good idea to put this here :D
      - https://discordapp.com/api/webhooks/347631273948479491/4wGTEwmPgA4AfTiHdIty2qszWdtNRve8LxRzfZqlgbIrbf7BSrJqg5zAa-szACKQSdD_/slack
    on_success: always # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

cache: yarn


install:
  - yarn
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - chmod +x hugo

before_script:
  - yarn global add gulp-cli
  - mkdir binaries && mv hugo binaries/
  - export PATH=$PATH:$PWD/binaries/

script:
  - gulp build
