language: node_js
sudo: true
dist: trusty

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install -g gulp
  - npm install
  - apt get install wget -y
  - curl -O https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-32bit.deb
  - dpkg -i hugo_0.26_Linux-32bit.deb

script:
  - hugo
  - gulp build
