language: node_js
sudo: true
dist: trusty

node_js:
  - "node"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/347631273948479491/4wGTEwmPgA4AfTiHdIty2qszWdtNRve8LxRzfZqlgbIrbf7BSrJqg5zAa-szACKQSdD_
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm

install:
  - npm install
  - curl -O https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-32bit.deb
  - dpkg -i hugo_0.26_Linux-32bit.deb

before_script:
  - npm install -g gulp-cli

script:
  - hugo
  - gulp build
