baseURL = "https://csec.infosecgur.us"
languageCode = "fr-FR"
title = "Le Comptoir Sécu"
MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
copyright = "© 2017 Le Comptoir Sécu"
paginate = 12
rssLimit = 30

[params]
author = "L'équipe du Comptoir Sécu"
contact = "contact@comptoirsecu.fr"
shortDesc = "Le Comptoir Sécu est un podcast traitant de la cybersécurité à travers des dossiers thématiques et des revues de l'actualité spécialisée."
longDesc = "Animé par 3 jeunes ingénieurs évoluant dans le domaine, ce podcast mensuel traite des différentes problématiques de la sécurité informatique. Toujours dans la bonne humeur, on échange sur l’actualité, réalise des dossiers sur des sujets techniques, partage les opinions de chacuns lors de débats… Alors, n’hésitez pas, et venez nous rejoindre au Comptoir Sécu"

[permalinks]
podcast = "/podcast/:title/"
sechebdo = "/sechebdo/:title/"
annonce = "/annonce/:title/"
article = "/article/:title/"
video = "/video/:title/"


[outputFormats]
[outputFormats.podcastFeed]
name = "podcastFeed"
mediatype = "application/rss"
Path = "/feed/"
baseName = "podcast"


[outputs]
home = [ "HTML", "podcastFeed"]
page = [ "HTML"]


[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
drink = "drinks"
song = "songs"
guest = "guests"

[menu]
  [[menu.left]]
      name= "Blog"
      pre = "fa-pencil"
      weight = 20
      identifier = "blog"
      url = "/article/"
      [[menu.left]]
          name= "Annonces"
          parent = "blog"
          weight = 21
          identifier = "annonce"
          url = "/annonce/"
      [[menu.left]]
          name= "Articles"
          parent = "blog"
          weight = 22
          identifier = "article"
          url = "/article/"
  [[menu.left]]
      name = "Podcasts"
      pre = "fa-microphone"
      weight = 30
      identifier = "podcast"
      url = "/podcast/"
      [[menu.left]]
          name = "Émissions"
          parent = "podcast"
          weight = 31
          identifier = "emission"
          url = "/categories/emission/"
      [[menu.left]]
          name = "Hors Séries"
          parent = "podcast"
          weight = 32
          identifier = "hors-serie"
          url = "/categories/hors-serie/"
  [[menu.left]]
      name= "Vidéos"
      pre = "fa-video-camera"
      weight = 40
      identifier = "video"
      url = "/video/"
      [[menu.left]]
          name= "SECompris"
          parent = "video"
          weight = 41
          identifier = "secompris"
          url = "/categories/secompris/"
      [[menu.left]]
          name= "SEClair"
          parent = "video"
          weight = 42
          identifier = "seclair"
          url = "/categories/seclair/"
      [[menu.left]]
          name= "PoC"
          parent = "video"
          weight = 43
          identifier = "poc"
          url = "/categories/poc/"
      [[menu.left]]
          name= "Point Sécu"
          parent = "video"
          weight = 43
          identifier = "point-secu"
          url = "https://www.youtube.com/channel/UCe-0FAoHZyDLPMLHnYAuXsw"
  [[menu.left]]
      name= "SecHebdos"
      pre = "fa-newspaper-o"
      weight = 50
      identifier = "sechebdo"
      url = "/sechebdo/"
  [[menu.left]]
      name= "Registres"
      pre = "fa-book"
      weight = 60
      identifier = "registre"
      [[menu.left]]
          name= "Membres"
          parent = "registre"
          weight = 61
          identifier = "membres"
          url="/authors/"
      [[menu.left]]
          name= "Invités"
          parent = "registre"
          weight = 62
          identifier = "invites"
          url="/guests/"
      [[menu.left]]
          name= "Boissons"
          parent = "registre"
          weight = 63
          identifier = "boissons"
          url="/drinks/"
      [[menu.left]]
          name= "Musiques"
          parent = "registre"
          weight = 64
          identifier = "musiques"
          url="/songs/"
  [[menu.right]]
      name= "Recherche"
      pre = "fa-search"
      weight = 70
      url = "/recherche/"
      identifier = "search"
  [[menu.footer]]
      name= "À propos"
      pre = "fa-info-circle"
      weight = 60
      identifier = "apropos"
      url = "/apropos/"
