version: "3"
services:
  csec-hugo:
    build:
      context: ./docker/hugo
      args:
        HUGO_GID: 1000
        HUGO_UID: 1000
    image: csec-hugo
    # depends_on:
      # - csec-dependencies
    ports:
      - 1313:1313
    volumes:
      - .:/app:rw

  csec-dependencies:
    build: ./docker/node
    image: csec-dependencies
    volumes:
      - .:/app:rw
