version: "3"
services:
  csec-hugo:
    build: ./docker/hugo
    depends_on:
      - csec-dependencies
    image: csec-hugo
    ports:
      - 1313:1313
    volumes:
      - .:/app:rw

  csec-dependencies:
    build: ./docker/node
    image: csec-dependencies
    volumes:
      - .:/app:rw
